### ISSUE TITLE
row-wise map function (calculation)

### ISSUE THREAD

**Issue by mejymejy** [SEL-Columbia/bamboo#106]
we need a function to map discrete values (possibly ranges or boolean expressions?) to another value.  an example of this would be assigning a demand to a row (facility) based on one or more attributes of that row (let's say a field called facility_type):

health_post -> 500 kWh/y
health_centre -> 10,000 kWh/y
hospital -> 50,000 kWh/y

not sure what the syntax should be for this, possibly something like:

`map(facility_type, 'health_post': 500, 'health_centre': 10000, 'hospital': 50000)`

or, we could generalize to a form of boolean expression -> discrete value doing something like:

`map(facility_type = 'health_post': 500, facility_type = 'health_centre': 10000, facility_type = 'hospital': 50000)`

this might give a bit more expressiveness in terms of the type of functions that we can offer (e.g. ranges or numerical comparisons).  also maybe we can use '->' instead of ':' for the map... not sure what is the most intuitive for the average user.

**Comment by prabhasp** [comment]
note that an "else" catch-all might be useful as well.
in terms of your propositions, i'd go with the latter, as the former can't
really deal with decimal valued objects, for ex.
and last, a comment: this could be emulated with ifs / ternary operators.
but the map would be more convenient to specify, and we should support.

On Thu, Aug 2, 2012 at 6:57 PM, Mark Johnston <
reply@reply.github.com

> wrote:
> 
> we need a function to map discrete values (possibly ranges or boolean
> expressions?) to another value.  an example of this would be assigning a
> demand to a row (facility) based on one or more attributes of that row
> (let's say a field called facility_type):
> 
> health_post -> 500 kWh/y
> health_centre -> 10,000 kWh/y
> hospital -> 50,000 kWh/y
> 
> not sure what the syntax should be for this, possibly something like:
> 
> `map(facility_type, 'health_post': 500, 'health_centre': 10000,
> 'hospital': 50000)`
> 
> or, we could generalize to a form of boolean expression -> discrete value
> doing something like:
> 
> `map(facility_type = 'health_post': 500, facility_type =
> 'health_centre': 10000, facility_type = 'hospital': 50000)`
> 
> this might give a bit more expressiveness in terms of the type of
> functions that we can offer (e.g. ranges or numerical comparisons).  also
> maybe we can use '->' instead of ':' for the map... not sure what is the
> most intuitive for the average user.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/modilabs/bamboo/issues/106

## 

Prabhas Pokharel
http://twitter.com/prabhasp
US mobile: +1 347 948 7654
skype/facebook/whatever: prabhasp

**Comment by mejymejy** [comment]
yeah, i like the logical style.  i feel like it is a bit more readable and intuitive for non-programmers.  thinking something like this:

`if food_type in ["morning_food"]: 1; if food_type in ["lunch"]: 2; if food_type in ["dinner"]: 3; else: 4`

cascaded if clauses with an optional else clause.
