### ISSUE TITLE
reorganize project directory

### ISSUE THREAD

**Issue by mejymejy** [SEL-Columbia/bamboo#108]
there is some basic moving around of stuff that should happen including:
- moving the actual source code into a directory called "bamboo"
- consolidating config dir (move to bamboo?)
- because of the setup of lib/ and tests/lib one cannot have a tests/lib/**init**.py which disallows running those tests via their python modules (more of an annoyance than anything).  this should be fixed to somehow allow this

open questions:
- where should tests live? (probably inside bamboo, but this doesn't address the test issue above)
- where to put requirements files and fabfile?

**Comment by pld** [comment]
now here, https://github.com/modilabs/bamboo/tree/refactor

**Comment by pld** [comment]
tests live in bamoo, req and fab not moved, havn't solved tests lib problem, config dir in bamboo
