### ISSUE TITLE
return _id column

### ISSUE THREAD

**Issue by mejymejy** [SEL-Columbia/bamboo#111]
how do we want to deal with this?  the original thought was to allow this column and internally add a prefix so that we could handle it like any other column, returning the name to _id when we return it to the user.  note: this is an issue with _id being a reserved key in mongo and we don't want to arbitrarily rule out the use of a column names _id.  this is how things are currently set up but we are not returning the _id column when we retrieve the dataset.  however, this is actually sort of a pain and i don't really think that it is a big deal if we rule out columns named _id for the sake of making life easier... at least for now.  think: this must be carried all the way through the code (calculations, etc.)  in any case, there is an error right now in the tests that we will ignore for now until this issue is resolved (see NOTE in tests/controllers/test_datasets.py)

**Comment by prabhasp** [comment]
is this about disallowing datasets with _id column in them? ... that seems
reasonable to me, with a low-priority bug report to fix this long-term.

On Tue, Aug 14, 2012 at 4:37 PM, Mark Johnston notifications@github.comwrote:

> how do we want to deal with this? the original thought was to allow this
> column and internally add a prefix so that we could handle it like any
> other column, returning the name to _id when we return it to the user.
> note: this is an issue with _id being a reserved key in mongo and we don't
> want to arbitrarily rule out the use of a column names _id. this is how
> things are currently set up but we are not returning the _id column when we
> retrieve the dataset. however, this is actually sort of a pain and i don't
> really think that it is a big deal if we rule out columns named _id for the
> sake of making life easier... at least for now. think: this must be carried
> all the way through the code (calculations, etc.) in any case, there is an
> error right now in the tests that we will ignore for now until this issue
> is resolved (see NOTE in tests/controllers/test_datasets.py)
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/modilabs/bamboo/issues/111.

## 

Prabhas Pokharel
http://twitter.com/prabhasp
US mobile: +1 347 948 7654
skype/facebook/whatever: prabhasp

**Comment by pld** [comment]
I thought this was working before, isn't there a _id in our test set?

**Comment by mejymejy** [comment]
this issue's scope is changed to the following:

currently the _id column is not being returned as part of the dataset if there is such a column.  this should be returned and there should be tests to ensure that it happens
