### ISSUE TITLE
store schema for dataset

### ISSUE THREAD

**Issue by pld** [SEL-Columbia/bamboo#12]
- figure out datastructure on bamboo for storing the schema
  - does it just define datatypes?
  - how to add type information to the schema

**Comment by prabhasp** [comment]
schema for formhub has, essentially, type/name/label / maybe more
label is useful: tells you how the original question was asked.
maybe more depends on type, and maybe useful as well. for example, if its a
select, there is a 'children' in the maybe more that has the labels. if it
is a calculate, it has a formula.

i think we should keep all of this linkage. not requiring it is nice, but
having it, to me, sounds useful.

On Thu, May 3, 2012 at 10:47 AM, Peter Lubell-Doughtie <
reply@reply.github.com

> wrote:
> - figure out datastructure on bamboo for storing the schema
>   - does it just define datatypes?
>   - how to add type information to the schema
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/modilabs/bamboo/issues/12

## 

Prabhas Pokharel
http://twitter.com/prabhasp
Nepal mobile: +977 98137 91044
US mobile: +1 347 948 7654
skype/facebook/whatever: prabhasp

**Comment by pld** [comment]
+1

**Comment by pld** [comment]
This will do this, https://github.com/modilabs/bamboo/issues/50
