### ISSUE TITLE
api call takes very long for larger datasets

### ISSUE THREAD

**Issue by myf** [SEL-Columbia/bamboo#127]
two issues from observation
- for the north_ghana water dataset I did group_by water_manager_name which supposed to be unique values of 255 submissions. The query took 8:50 minutes to run.
- the simplest queries takes about 7~9 seconds to run that was way longer than internet latency

@prabhasp indexed the mongodb collections and that seems to fixed the query problem and reduced the north_ghana water_manager_name to ~1:30 from 8:50. great success!

any other thought on that?

for now we would like to restrict queries to <30 unique names after group by which returns result aftere ~3s

**Comment by prabhasp** [comment]
Adding some detail:
- the "water_manager_name" group by asks bamboo to group by a field with
  255 unique names. This does not really make sense. What makes sense? Well,
  we don't know very well, but the plan is to limit group_by queries to a
  max_group_by_number, which is set to 30 for now. (Improvement here is
  needed).
  - This took 8 min 50 seconds before indexing, 1:30 after. 1:30 is
    still long, likely shouldn't be allowed.
- "other queries", ie group by queries with the group by field having <
  30 elements, took 7-9 seconds before indexing, <= 3 seconds after indexing
  on a 30-element group, and <= 2 seconds for a groupby on a <30-element
  group.

On Thu, Sep 6, 2012 at 12:42 PM, Myf Ma notifications@github.com wrote:

> two issues from observation
> - for the north_ghana water dataset I did group_by water_manager_name
>   which supposed to be unique values of 255 submissions. The query took 8:50
>   minutes to run.
> - the simplest queries takes about 7~9 seconds to run that was way
>   longer than internet latency
> 
> @prabhasp https://github.com/prabhasp indexed the mongodb collections
> and that seems to fixed the query problem and reduced the north_ghana
> water_manager_name to ~1:30 from 8:50. great success!
> 
> any other thought on that?
> 
> for now we would like to restrict queries to <30 unique names after group
> by which returns result aftere ~3s
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/modilabs/bamboo/issues/127.

## 

Prabhas Pokharel
http://twitter.com/prabhasp
US mobile: +1 347 948 7654
skype/facebook/whatever: prabhasp

**Comment by pld** [comment]
@myf can you make a python script to add the indices that you just did to the database?

see http://api.mongodb.org/python/current/api/pymongo/collection.html#pymongo.collection.Collection.create_index

For now it can go into `bamboo/config`.  Later it may be worthwhile to make a `db` folder somewhere.

**Comment by myf** [comment]
yup

**Comment by myf** [comment]
in mongo_indexing branch
