### ISSUE TITLE
Group by default to grouping on a single column

### ISSUE THREAD

**Issue by pld** [SEL-Columbia/bamboo#136]
With option to pass multiple columns and (maybe) a special indicator for all

**Comment by pld** [comment]
this is cached

**Comment by prabhasp** [comment]
Detail (and why overall general summary doesn't solve this problem).

Right now, if you want to analyze "amount" grouped by "food_type", you pass a query to bamboo saying

```
curl http://bamboo.io/datasets/8a3d74711475d8a51c84484fe73f24bd151242ea/summary?group=food_type
```

But this produces a result (when bamboo isn't returning 500s) that groups _every single column_ in this dataset by food_type. I don't need that, and in fact, asking for that should require extra effort. Instead, clients should be (1) allowed and (2) encouraged to run:

```
curl http://bamboo.io/datasets/8a3d74711475d8a51c84484fe73f24bd151242ea/summary?
    group=food_type&select='{"amount":1}'
```

or something of the sort. The semantics I am thinking of should be: passing a `group` is only allowed if `select` is also passed.

**Comment by pld** [comment]
Potential way to handle this is require a `select` (which can be an empty select must be explicit) to limit the returned data from mongo

**Comment by prabhasp** [comment]
Would the following parse properly (ie, generate `{"group": "food_type", "select": "", "foo: "bar"}`)?

```
curl http://bamboo.io/datasets/8a3d74711475d8a51c84484fe73f24bd151242ea/summary?group=food_type&select=&foo=bar
```

If so, +1. 
If no, proposal:

```
curl http://bamboo.io/datasets/8a3d74711475d8a51c84484fe73f24bd151242ea/summary?group=food_type&select=_ALL_
```

with a required select.

**Comment by pld** [comment]
The query would use a standard mongo select and look like:

`curl http://bamboo.io/datasets/8a3d74711475d8a51c84484fe73f24bd151242ea/summary?select='{"amount":1}'&group=food_type`

the marker could just be `select=all`

**Comment by prabhasp** [comment]
Sounds good.

prabhas pokharel
skype/twitter/fb: prabhasp
+1 347 9487654
