### ISSUE TITLE
Delay imports and downloads of large files

### ISSUE THREAD

**Issue by pld** [SEL-Columbia/bamboo#151]
On adding a new dataset reading the file from the remote URL and converting the file in a dataframe should happen in the background.

The infrastructure for converting is there, for loading the URL the changes should be in `lib/io.py`

**Comment by prabhasp** [comment]
question: will there be notifications / callbacks when we do this? (and
other delays on commands coming over http.)

**Comment by pld** [comment]
I suppose there should be when we need them, we should open an issue.  That will add some protocol overhead.

**Comment by modilabs-starscream** [comment]
Status for these uploads issue here, https://github.com/modilabs/bamboo/issues/161
