### ISSUE TITLE
Should linked datasets deleted when their parent is deleted?

### ISSUE THREAD

**Issue by pld** [SEL-Columbia/bamboo#156]
Currently they are not.  This is where linked datasets are the results of aggregations.

**Comment by prabhasp** [comment]
and separately, should they be? i coule see reason for both. whichever
choice it is, should be documented.

On Mon, Oct 1, 2012 at 9:45 AM, Peter Lubell-Doughtie <
notifications@github.com> wrote:

> Where linked datasets are the results of aggregations.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/modilabs/bamboo/issues/156.

## 

Prabhas Pokharel
http://twitter.com/prabhasp
US mobile: +1 347 948 7654
skype/facebook/whatever: prabhasp

**Comment by pld** [comment]
my mistake, that's what I meant: should they be.  I'm going to say they should not.

**Comment by pld** [comment]
They'll stay around

**Comment by prabhasp** [comment]
+.5
