### ISSUE TITLE
Building indicators

### ISSUE THREAD

**Issue by pld** [SEL-Columbia/bamboo#16]
- formula with canonical name for arguments and results
  - e.g. `student_teacher_ratio := num_teachers / num_students`
- user defined mapping between their columns names and columns required by formula,
  - `num_teachers: my_num_teachers`
  - `num_students: my_num_girl + my_num_boys`
- or
  - `num_teachers: my_num_teachers`
  - `num_students: my_num_students`

**Comment by prabhasp** [comment]
Calculations objects have the following properties

```
name
formula
dataset_id      # the dataset this calculation is linked to
[output_type]   # can be undefined / user-defined in beginning
```

the following functions

```
evaluate          #returns value (when called on a row for row-level calculations)
validate          #returns whether this is a valid calculation (on this dataset)
[dependencies]    #returns all the other columns / calculations that this calculation depends on
```

Aggregate calculations will be some sort of derived objects that optionally have the following function:

```
 reduce(prev_result, new_observation[s]) => new_result
```

Aggregation functions will be custom defined within bamboo, examples maybe `count_true(${solar_functional})` `ratio(${num_students},${num_teachers})` etc.

**Comment by pld** [comment]
Some options for parsing calculations:
- http://fdik.org/pyPEG/
- http://pyparsing.wikispaces.com/
- http://www.dabeaz.com/ply/ (there's a list of more at the bottom of the page)

A whole bunch listed here http://nedbatchelder.com/text/python-parsers.html
