### ISSUE TITLE
Performance testing on reasonably large dataset: use vbench or another automated tool

### ISSUE THREAD

**Issue by pld** [SEL-Columbia/bamboo#18]
Stats for
- insert
- summary statistics
- summary statistics with group
- calculations
- aggregations
- update dataset (and calcs/aggs accordingly)

**Comment by prabhasp** [comment]
including groupby plz.

On Mon, May 7, 2012 at 6:12 PM, Peter Lubell-Doughtie <
reply@reply.github.com

> wrote:
> - insert, summary stats
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/modilabs/bamboo/issues/18

## 

Prabhas Pokharel
http://twitter.com/prabhasp
Nepal mobile: +977 98137 91044
US mobile: +1 347 948 7654
skype/facebook/whatever: prabhasp

**Comment by pld** [comment]
for sure, updated

**Comment by pld** [comment]
data path: `../tests/fixtures/good_eats.csv`

---

post time: `0.017229785`
get time: `0.015992841`
summary time: `0.016174195`
group time: `0.016432174`

more on the way

**Comment by pld** [comment]
add vbench to automate performance testing
- https://github.com/pydata/vbench
- http://wesmckinney.com/blog/?p=373
