### ISSUE TITLE
how to handle updates for columns that need to be renamed?

### ISSUE THREAD

**Issue by mejymejy** [SEL-Columbia/bamboo#208]
currently when we import a dataset we convert all spaces and special characters in the column names into underscores so that the resulting columns have names that only consist of alphanums and underscores.  the reasoning behind this is that in order to support row calculations the column must be able to be referenced unambiguously in the calculation parser.

for example, consider a dataset with columns named `x` and `x + 1`.  if i was to add a calculation to this dataset with a formula `x + 1 * 2` there would be a problem with parsing because the result tree is ambiguous and gives differing results for the different interpretations.  it could either be the column `x + 1` times 2 (equal to 4 for x = 1) or the column `x` plus 2 (equal to 3 for x = 1).  this is an unfortunate situation which can be avoided by forcing the column names to have unique ("slugified") names since each column reference becomes unambiguous.

fine.  this seems reasonable, right?  the issue now becomes how to map the original column names to slugified versions.  as was stated before, for the time being we convert all special characters and spaces to underscores.  this gives nice column names like `number_of_students` for "Number of Students" but not so nice names like `x___1` for columns named "x + 1".  what if you add a column named "x - 1" to this same dataset?  our "solution" is to give this column the name `x___1_` since it would originally be mapped to `x___1` but that column already exists.  what originally seemed like a decent scheme for mapping has left us with strangely named columns that are very awkward and lacking any real semantics.

this is further complicated by the update feature for datasets.  we allow a PUT request to apply a JSON list of row data in (column name, value) pairs to any existing dataset.  since these column names may be coming from the same place that the dataset was created from (e.g. formhub) the renaming must happen here as well.  in formhub, much of the data is stored in group heirarchies such as "food/type" and "food/quality" and so these get renamed to `food_type` and `food_quality`.  this is fine, though the updates will come in the first form and must be correctly matched with the already-renamed columns in the existing dataset.  we do not allow schema changes within an update (the routine will only allow one to add values for columns that already exist in the dataset as well as fill in n/a values for any columns not supplied in the JSON).  this can become a problem because even with a reproducible scheme for translating the original column names to slugified versions, a partial update (one that only updates a subset of the columns in the dataset) may incorrectly map columns in the update given our current scheme.

we cannot completely prevent a user from mangling their data, but it would be nice to have a means to convert datasets to meaningful schemas that retain an easy-to-update workflow.  i think that we should preserve the notion of slugifying columns in a way that allows them to be unambiguous and semantic representations of the original names, though i am not sure that our current scheme accomplished this very well.  side note: our scheme will explode unicode into a bunch of underscores and all meaning of the column names will be lost!  it would be nice to allow updates to come in the form that the original dataset was created by.  one idea would be to allow updates to use the original name for the column (which i believe we store in the `name` or `label` field of the schema).  this would allow either the name or the slug to be used.  anyways, @pld @prabhasp what do you guys think about this?  i have written way too much already...

**Comment by prabhasp** [comment]
two options i see:
- keep a mapping in bamboo (ie, ["x__1": "x+1", "x-1": "x__1_"], etc.)
  somewhere so that the user (+ client software) that are not writing
  calculations can re-reference it, and reference this during updates.
- force the use of quotes when column names with spaces appear. csv uses
  this method, so a cell can contain the value "plus, and minus" if it is
  enclosed by quotes. ie, "x+1" + 1 would be allowed.

and finally, a combination of both might be best:
- auto migrate x+1 to "x+1" instead of "x__1". This makes collissions
  impossible (i believe), and doesn't have semantics loss issues. The rule is
  that in calculations, it has to be reference as "x+1"; so x+1+1 = x+2
  whereas "x+1"+1 is the column with name "x+1" + 1.

On Fri, Oct 5, 2012 at 1:20 PM, Mark Johnston notifications@github.comwrote:

> currently when we import a dataset we convert all spaces and special
> characters in the column names into underscores so that the resulting
> columns have names that only consist of alphanums and underscores. the
> reasoning behind this is that in order to support row calculations the
> column must be able to be referenced unambiguously in the calculation
> parser.
> 
> for example, consider a dataset with columns named x and x + 1. if i was
> to add a calculation to this dataset with a formula x + 1 \* 2 there would
> be a problem with parsing because the result tree is ambiguous and gives
> differing results for the different interpretations. it could either be the
> column x + 1 times 2 (equal to 4 for x = 1) or the column x plus 2 (equal
> to 3 for x = 1). this is an unfortunate situation which can be avoided by
> forcing the column names to have unique ("slugified") names since each
> column reference becomes unambiguous.
> 
> fine. this seems reasonable, right? the issue now becomes how to map the
> original column names to slugified versions. as was stated before, for the
> time being we convert all special characters and spaces to underscores.
> this gives nice column names like number_of_students for "Number of
> Students" but not so nice names like x___1 for columns named "x + 1".
> what if you add a column named "x - 1" to this same dataset? our "solution"
> is to give this column the name x___1_ since it would originally be
> mapped to x___1 but that column already exists. what originally seemed
> like a decent scheme for mapping has left us with strangely named columns
> that are very awkward and lacking any real semantics.
> 
> this is further complicated by the update feature for datasets. we allow a
> PUT request to apply a JSON list of row data in (column name, value) pairs
> to any existing dataset. since these column names may be coming from the
> same place that the dataset was created from (e.g. formhub) the renaming
> must happen here as well. in formhub, much of the data is stored in group
> heirarchies such as "food/type" and "food/quality" and so these get renamed
> to food_type and food_quality. this is fine, though the updates will come
> in the first form and must be correctly matched with the already-renamed
> columns in the existing dataset. we do not allow schema changes within an
> update (the routine will only allow one to add values for columns that
> already exist in the dataset as well as fill in n/a values for any columns
> not supplied in the JSON). this can become a problem because even with a
> reproducible scheme for translating the original column names to slugified
> versions, a partial update (one that only updates a subset of the columns
> in the dataset) may incorrectly map columns in the update given our current
> scheme.
> 
> we cannot completely prevent a user from mangling their data, but it would
> be nice to have a means to convert datasets to meaningful schemas that
> retain an easy-to-update workflow. i think that we should preserve the
> notion of slugifying columns in a way that allows them to be unambiguous
> and semantic representations of the original names, though i am not sure
> that our current scheme accomplished this very well. side note: our scheme
> will explode unicode into a bunch of underscores and all meaning of the
> column names will be lost! it would be nice to allow updates to come in the
> form that the original dataset was created by. one idea would be to allow
> updates to use the original name for the column (which i believe we store
> in the name or label field of the schema). this would allow either the
> name or the slug to be used. anyways, @pld https://github.com/pld
> @prabhasp https://github.com/prabhasp what do you guys think about
> this? i have written way too much already...
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/modilabs/bamboo/issues/208.

## 

Prabhas Pokharel
http://twitter.com/prabhasp
US mobile: +1 347 948 7654
skype/facebook/whatever: prabhasp

**Comment by pld** [comment]
I don't think this is actually an issue, the test schema (the first row in the test csv uses food_type) so the update should use food_type.  If that row said food/type the schema would have this and map it to food_type, the problem is the the update JSON is wrong (isn't doesn't match the csv).
