### ISSUE TITLE
allow row update by supplying column label

### ISSUE THREAD

**Issue by mejymejy** [SEL-Columbia/bamboo#212]
currently for updates you must reference columns in the JSON via their label (i.e. their original format before being slugified) but we should also allow them to be referenced by their slugified versions

**Comment by prabhasp** [comment]
Thought: what if you kept the slugified version hidden? On every write, slugify before writing, and on every read, de-slugify before reading. Then, you reduce the level of complexity in clients = win!
[edit: this would force calculation references to be quoted. but a solid argument says: so be it. Perhaps we get Roger's feedback?]
