### ISSUE TITLE
How do you merge a new column into a dataset?

### ISSUE THREAD

**Issue by prabhasp** [SEL-Columbia/bamboo#234]
Need the functionality to do the following. Need to pass:

```
{{lga: 'abia', population: 1000}, {lga: 'nasarawa', population:2000}, ...}
```

into a dataset that already has a column called `lga`, and specify that `population` should be added. The logic being that afterwards, for each row in the existing dataset where `lga` is `abia` population column with value 1000 should be added, for each row where `lga` is `nasarawa`, population column with value 2000 should be added, and for all rows where `lga` is something unspecified in this command, `NA` should be added.

Reason this is phrased as a question: I believe this is already possible with the `map` functionality of bamboo; will figure out how to make that happen.

**Comment by mejymejy** [comment]
you can achieve this with a case statement, i believe it would be:

`case lga in ["abia"]: 1000, lga in ["nasarawa"]: 2000`

though that will fill in `n/a` for all other lgas.  if you want to supply a default, you can add it like so:

`case lga in ["abia"]: 1000, lga in ["nasarawa"]: 2000, default: 0`

**Comment by pld** [comment]
@prabhasp does that close the issue?
