### ISSUE TITLE
Calculate cadinality for columns that are measures

### ISSUE THREAD

**Issue by pld** [SEL-Columbia/bamboo#266]
Right now, only being calculated for those that are dimensions.

**Comment by prabhasp** [comment]
What does this mean, for example, for an int? The [min,max]?

**Comment by pld** [comment]
The number of unique entries, as thought you had cast all the values to a string

**Comment by prabhasp** [comment]
Interesting. Does this even make sense for doubles? To me, ranges feel like
the equivalent of cardinality of dimensions for measures.

On Thursday, November 8, 2012, Peter Lubell-Doughtie wrote:

> The number of unique entries, as thought you had cast all the values to a
> string
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/modilabs/bamboo/issues/266#issuecomment-10204746.

## 

Prabhas Pokharel
http://twitter.com/prabhasp
US mobile: +1 347 948 7654
skype/facebook/whatever: prabhasp

**Comment by pld** [comment]
I agree it makes less sense for doubles, although it's a quick way to check if your column has all unique values.
