### ISSUE TITLE
Set save batch size based on the width of dataset

### ISSUE THREAD

**Issue by pld** [SEL-Columbia/bamboo#270]
- set save batch size based on size of each row (somehow accounting for the max size of data in the row)
- max save size for MongoDB is 16MB, set batch size to be below this

**Comment by mejymejy** [comment]
we have to be careful with this since it also depends on the size of the data in the columns...  maybe we try to find some kind of upper-bound?  or if we can somehow assess the size of each document then we could keep a running tally of space used and set the batch size to be just under the limit

**Comment by prabhasp** [comment]
What happens when batch size is too big? If it's an exception, then catch
it, retry with half the size may be fine, binary search style?
If important, can save batch size per dataset for future use.

prabhas pokharel
skype/twitter/fb: prabhasp
+1 347 9487654

**Comment by mejymejy** [comment]
dataset import is failing with the default setting `DB_SAVE_BATCH_SIZE = 3000` for wide nigeria dataset (health has 350+ columns).  lowered it to 2000 and it works.  [this](http://api.mongodb.org/python/current/api/pymongo/errors.html#pymongo.errors.AutoReconnect) is the error that you get when the size is too big... we might be able to catch it and re-batch.  for now, we can set the size to 2000 so things will work and investigate this issue further.  make this a priority for the next iteration?

**Comment by pld** [comment]
Yeah, added to 0.6.  Could we catch the error, drop the batch size and retry?
