### ISSUE TITLE
Joined dataset is not update-able

### ISSUE THREAD

**Issue by rgaudin** [SEL-Columbia/bamboo#292]
Datasets created by joining two dataset are not update-able.
Bamboo accepts the update but doesn't show the data nor updates the row counters.

Since joined datasets are supposed to be updated automatically from updates on each individual datasets, we shouldn't update those directly.
So it's not blocking but I believe it highlights a malfunction.
1. Join two datasets
2. Send an update data
3. Check the `/info`
   It should have updated the `rows` field but hasn't. Querying the data doesn't show data neither.

```
curl -d 'schema={"name": {"simpletype": "string", "olap_type": "measure", "label": "name"}, "formhub/uuid": {"simpletype": "string", "olap_type": "dimension", "label": "formhub/uuid"}}' http://bamboo.io/datasets

curl -d 'schema={"age": {"simpletype": "integer", "olap_type": "measure", "label": "age"}, "formhub/uuid": {"simpletype": "string", "olap_type": "dimension", "label": "formhub/uuid"}}' http://bamboo.io/datasets

curl -X POST -d "dataset_id=XXXX&other_dataset_id=XXXX&on=formhub/uuid" http://bamboo.io/datasets/join

curl -X PUT -H "Accept: application/json" -H "Content-type: application/json" -d '{"formhub/uuid": "num2", "name": "reg", "age": 3}' http://bamboo.io/datasets/XXX
```

**Comment by pld** [comment]
duplicate https://github.com/modilabs/bamboo/issues/293
