### ISSUE TITLE
Updates to schema-driven dataset changes the schema

### ISSUE THREAD

**Issue by rgaudin** [SEL-Columbia/bamboo#294]
When a dataset is created from a schema, it starts empty but advertises the proper number of columns (from the schema).

Once updated, the schema used for creation is forgotten in favor of the shape of the data in the dframe.
If for some reason (early updates), the data doesn't correspond completely to the schema, it void the advantage of using a schema.
1. Create a dataset with 2 fields (schema)
2. send an update with data for only one field.
3. Query the schema on `/info`. Other field is gone both in `schema` and `columns`.

```
curl -d 'schema={"name": {"simpletype": "string", "olap_type": "measure", "label": "name"}, "age": {"simpletype": "integer", "olap_type": "measure", "label": "age"}}' http://bamboo.io/datasets

=> {"id": "XXXX"}

curl -X PUT -H "Accept: application/json" -H "Content-type: application/json" -d '{"name": "reg"}' http://bamboo.io/datasets/XXXX

curl http://bamboo.io/datasets/XXXX/info
```

**Comment by pld** [comment]
http://bamboo.io/docs/models.html#bamboo.models.dataset.Dataset.build_schema
