### ISSUE TITLE
Deprecate passing data as whole POST body

### ISSUE THREAD

**Issue by pld** [SEL-Columbia/bamboo#296]
I think only in update is the entire body of the POST read, as the update file.  This is opposed to the command having an assignment, like `update=[JSON]`.

http://bamboo.io/docs/advanced_commands.html#updating-your-data

This doesn't fit with the rest of the code.  We should we change the update so that the JSON is passed as a parameter (still in the post body).

As happens
http://bamboo.io/docs/basic_commands.html#storing-data-in-bamboo
http://bamboo.io/docs/advanced_commands.html#creating-a-dataset-from-a-schema
http://bamboo.io/docs/advanced_commands.html#creating-multiple-calculations-via-json

**Comment by prabhasp** [comment]
+1 towards yes.

**Comment by pld** [comment]
closed by https://github.com/modilabs/bamboo/pull/308
