### ISSUE TITLE
use DataFrame.get_value() if appropriate

### ISSUE THREAD

**Issue by mejymejy** [SEL-Columbia/bamboo#297]
supposedly this is faster... just found it in the docs

http://pandas.pydata.org/pandas-docs/stable/indexing.html#fast-scalar-value-getting-and-setting

**Comment by mejymejy** [comment]
note that this is for scalar reference.  the difference is quite large in terms of relative time, but either way the operation is pretty quick.  i doubt that this is a large issue for us since scalar value read/write is not something that we do often (though it would be good to find) and the difference is going to be overwhelmed by other operations.  still, for the curious (10k x 65 dataset):

```
In [10]: %timeit df['uuid'][0]
100000 loops, best of 3: 6.91 us per loop

In [11]: %timeit df.get_value(0, 'uuid')
100000 loops, best of 3: 2.63 us per loop
```

**Comment by pld** [comment]
OK, closing this, I don't think `get_value` is not being used anywhere it could be.
