### ISSUE TITLE
cache calculations

### ISSUE THREAD

**Issue by pld** [SEL-Columbia/bamboo#3]
- should we cache calulations?
  - tied to hash
- do we also prime them?
  - create on upload of data, asynchronously
  - otherwise you'll get a delay on first pull

**Comment by prabhasp** [comment]
+1
on priming, +0.

On Thu, Apr 26, 2012 at 10:25 AM, Peter Lubell-Doughtie <
reply@reply.github.com

> wrote:
> - should we cache calulations?
>   - tied to hash
> - do we also prime them?
>   - create on upload of data, asynchronously
>   - otherwise you'll get a delay on first pull
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/modilabs/bamboo/issues/3

## 

Prabhas Pokharel
http://twitter.com/prabhasp
Nepal mobile: +977 98137 91044
US mobile: +1 347 948 7654
skype/facebook/whatever: prabhasp

**Comment by pld** [comment]
ok, for now we'll cache, no priming

**Comment by pld** [comment]
https://github.com/modilabs/bamboo/issues/15
