### ISSUE TITLE
upgrade kombu

### ISSUE THREAD

**Issue by mejymejy** [SEL-Columbia/bamboo#300]
not a major priority but it would be a good idea to get a sense of what versions our dependent libraries are at.  we keep up with pandas quite well but some of the other ones we have kept still for stability's sake.  let's list what we find in the comments here.

**Comment by mejymejy** [comment]
kombu 2.5 released (we use 2.4.7)

**Comment by pld** [comment]
Let's create a separate issue for each lib we need to/think should get upgraded.
