### ISSUE TITLE
only pull relevant columns into a df when calculating

### ISSUE THREAD

**Issue by mejymejy** [SEL-Columbia/bamboo#321]
When performing operations on a dataset only pull from MongoDB the columns needed for that operation.

**Comment by pld** [comment]
as in use a select in the Mongo query?  that makes sense, but I wonder if it would have a significant affect on speed, it might not.

**Comment by mejymejy** [comment]
yeah, exactly.  i'm not sure either.  i know we have mentioned some sort of vbench thing in the past.  is this something that we should try to do?

**Comment by pld** [comment]
At some point, but I think writing our own would be easier than using vbench.

**Comment by mejymejy** [comment]
even if this does not affect speed, we really need to watch memory usage, which this should help quite a bit.  i will look into this further.  one difference i see with how things work now is that we will need to use an update for the documents with the new column key as opposed to the delete/insert that we do now.  not sure how this will affect things.  i imagine that it is on par (or faster) since delete/insert of a bunch of large documents is probably not too different from an insert with a few keys on the same number.

**Comment by prabhasp** [comment]
we'll also have to think through indexing carefully in this process; that
is likely to have large speed effects.

On Mon, Mar 4, 2013 at 12:05 PM, Mark Johnston notifications@github.comwrote:

> even if this does not affect speed, we really need to watch memory usage,
> which this should help quite a bit. i will look into this further. one
> difference i see with how things work now is that we will need to use an
> update for the documents with the new column key as opposed to the
> delete/insert that we do now. not sure how this will affect things. i
> imagine that it is on par (or faster) since delete/insert of a bunch of
> large documents is probably not too different from an insert with a few
> keys on the same number.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/modilabs/bamboo/issues/321#issuecomment-14391751
> .

## 

Prabhas Pokharel
http://prabhasp.com
US mobile: +1 347 948 7654
twitter/skype/facebook/whatever: prabhasp

**Comment by myf** [comment]
the indexing script is at /bamboo/config/mongo_index.py i don't see it currently being referenced by any script.

**Comment by mejymejy** [comment]
i think it is ok for it not to be ran from other scripts, though we might want to add it to the fab deployment script.  as long as we put it in the docs maybe it is ok?  is there somewhere it would make sense to run it in the code?

**Comment by mejymejy** [comment]
these are the indices we are using now.  basically, the foreign keys that link the collections together.  not sure what other indices we can add by default to provide any performance gains.  we can try to add them based on usage, though i don't know how much we would gain...

datasets:

```
        ("BAMBOO_RESERVED_KEY_dataset_id", ASCENDING),
        ("BAMBOO_RESERVED_KEY_dataset_observation_id", ASCENDING)
```

observations:

```
        ("BAMBOO_RESERVED_KEY_dataset_observation_id", ASCENDING)
```

calculations:

```
        ("BAMBOO_RESERVED_KEY_dataset_id", ASCENDING)
```

**Comment by pld** [comment]
Indexing is a separate issue, which from @mejymejy's comment looks resolved.  Given we haven't modified the indexing script I don't think there's a reason to re-run every deploy.  When we write-up docs for running bamboo as a service we can include it there.  Again, this is a separate issue and we should have the discussion somewhere else.

About only the relevant columns, we should put some priority on this issue.  The `Dataset.dframe` method can take a `select` argument so the calculations should be able to figure out (from the columns they reference) what this select should be.

**Comment by prabhasp** [comment]
Actually, the reason I raised the index is that we might want something
like the following:

({"BAMBOO_RESERVED_KEY_dataset_id", "index"}, ASCENDING)

if we were to move to this scheme, and update only certain indices at
a time. +1 on putting some priority in the issue.

On Mon, Mar 4, 2013 at 1:42 PM, Peter Lubell-Doughtie <
notifications@github.com> wrote:

> Indexing is a separate issue, which from @mejymejyhttps://github.com/mejymejy's
> comment looks resolved. Given we haven't modified the indexing script I
> don't think there's a reason to re-run every deploy. When we write-up docs
> for running bamboo as a service we can include it there. Again, this is a
> separate issue and we should have the discussion somewhere else.
> 
> About only the relevant columns, we should put some priority on this
> issue. The Dataset.dframe method can take a select argument so the
> calculations should be able to figure out (from the columns they reference)
> what this select should be.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/modilabs/bamboo/issues/321#issuecomment-14397070
> .

## 

Prabhas Pokharel
http://prabhasp.com
US mobile: +1 347 948 7654
twitter/skype/facebook/whatever: prabhasp

**Comment by pld** [comment]
Maybe make a new issue for that, still not relevant here.

**Comment by pld** [comment]
I think this was closed by the calc-perf branch, indexing has been updated for changes in the encoded keys branch.
