### ISSUE TITLE
String concatenation formula

### ISSUE THREAD

**Issue by prabhasp** [SEL-Columbia/bamboo#323]
can bamboo do string concatenation now?

**Comment by pld** [comment]
No, was never in the plans.  This list is up to date: http://bamboo.io/docs/core.html#formula-parser

**Comment by prabhasp** [comment]
So this came up as a manipulation that was done for Nigeria work.
Haven't managed to turn everything into an issue, but the next plan for bamboo, which will help most crucially with performance reasoning, is to turn Nigeria analysis as something done in R to something done in bamboo. 

Will create a separate milestone called Nigeria manipulations or some such, and open an issue similar to this there.

**Comment by pld** [comment]
Sounds good, that should be generally useful.  I just want to make sure we do not end building a general purpose programming language.
