### ISSUE TITLE
Clearer docs for join, explain all edge cases

### ISSUE THREAD

**Issue by pld** [SEL-Columbia/bamboo#333]
- what happens with a non-unique lhs?
- what happens when an update makes the lhs non unique?
- is anything ever overwritten? (No)

Current docs: http://bamboo.io/docs/advanced_commands.html#joining-multiple-datasets

**Comment by rgaudin** [comment]
We also need to advertise that it's forbidden to join two datasets which share common column names. Right now it fails with a non-related error message.

Or maybe we can try to support that ; otherwise no formhub datasets will be join-able together (imei, today, etc).

**Comment by pld** [comment]
Noted.  We have two outstanding issues that can resolve this, #320 will allow you to drop the overlapping columns, better #152 which gives fine grained control over what colums will be in the merged dataset.
