### ISSUE TITLE
Unable to update joined dataset

### ISSUE THREAD

**Issue by rgaudin** [SEL-Columbia/bamboo#334]
If a dataset has been joined to another one, further updates to the original dataset doesn't work. bamboo just get stuck and eventually time out.

Replicate ?
1. Create dataset A
2. Create dataset B
3. Join both
4. Update dataset A or dataset B: won't work.

**Comment by pld** [comment]
Tests are for sync, https://github.com/modilabs/bamboo/blob/master/bamboo/tests/controllers/test_datasets_update_with_join.py

Guessing this is a regression for async, need to add tests for async joined updates.

**Comment by pld** [comment]
I can't replicate this.  I wrote async tests for the join code and they pass.  Maybe it is something specific to the data?  Maybe the tests are not correct?

Can you write a failing test case for us to look at?

**Comment by rgaudin** [comment]
OK, here's a super simple example that fails.
Can you please take a look? Reopening until we have an explanation.

```
(test)reg@elb ~/private/YELEMAN/SoilTracking (master) $ cat test_step1.csv 
barcode,name,date
12345,reg,1356361939
654321,alou,1356361940

(test)reg@elb ~/private/YELEMAN/SoilTracking (master) $ cat test_step2.csv 
barcode,name2,date2
12345,reg,1356363670
654321,alou,1356365671
777777,hello,1356366672

(test)reg@elb ~/private/YELEMAN/SoilTracking (master) $ curl -X POST -F csv_file=@test_step1.csv http://bamboo.io/datasets
{"id": "87407ab99f3b400a924aa34292ada03a"}

(test)reg@elb ~/private/YELEMAN/SoilTracking (master) $ curl -X POST -F csv_file=@test_step2.csv http://bamboo.io/datasets
{"id": "b3fd621b3ef84c4882c9ee0e070ca569"}

(test)reg@elb ~/private/YELEMAN/SoilTracking (master) $ curl -X POST -d "dataset_id=87407ab99f3b400a924aa34292ada03a&other_dataset_id=b3fd621b3ef84c4882c9ee0e070ca569&on=barcode" http://bamboo.io/datasets/join
{"id": "f3c8846caebc4f30b2f19ed0e2c46967", "success": "joined dataset b3fd621b3ef84c4882c9ee0e070ca569 to 87407ab99f3b400a924aa34292ada03a on barcode"}

(test)reg@elb ~/private/YELEMAN/SoilTracking (master) $ curl -X PUT -H "Accept: application/json" -H "Content-type: application/json" -d 'update={"barcode":22222,"name":"any","date_":1356361940}' http://bamboo.io/datasets/87407ab99f3b400a924aa34292ada03a
curl: (18) transfer closed with 716 bytes remaining to read
```

**Comment by pld** [comment]
I'll check this out tonight.  Are the two datasets to be joined are in the "ready" state when you join them and when the send an update?  (state information comes from an info call)

(This needs docs)

**Comment by rgaudin** [comment]
I believe they are (`/info` makes sense) although I don't see the `state` field anymore there.

**Comment by pld** [comment]
Thanks @rgaudin the tests were very helpful.  The docs are out of data, very sorry about that.  The command is simply

```
curl -X PUT -d 'update={"barcode":22222,"name":"any","date_":1356361940}' http://bamboo.io/datasets/87407ab99f3b400a924aa34292ada03a
```

See the result here: http://bamboo.io/datasets/87407ab99f3b400a924aa34292ada03a

I'll update the docs now as resolution for this issue.
