### ISSUE TITLE
usage error?

### ISSUE THREAD

**Issue by mberg** [SEL-Columbia/bamboo#345]
When I do this it looks like it works.  Eventhough the response doesn't match the docs.

curl -X POST -d "name=water_functioning_count&formula=count(water_functioning in [\"yes\"])&group=wards" http://bamboo.io/calculations/27bc0d25cb75463fa22d3993a707d4b1
{"success": "created calulcation: water_functioning_count for dataset: 27bc0d25cb75463fa22d3993a707d4b1"}

When I try and do this though:

curl -g http://bamboo.io/datasets/27bc0d25cb75463fa22d3993a707d4b1/related

I get a 404 response

**Comment by mberg** [comment]
note this works

http://bamboo.io/calculations/27bc0d25cb75463fa22d3993a707d4b1

**Comment by pld** [comment]
The docs are out of date, the command is now

```
curl -g http://bamboo.io/datasets/27bc0d25cb75463fa22d3993a707d4b1/aggregations
```
