### ISSUE TITLE
CSV Export

### ISSUE THREAD

**Issue by mberg** [SEL-Columbia/bamboo#348]
Do we want to have something for the first column name?  maybe id?

Also should we pad the strings with " "?

```
,communities,water_functioning_count
0,thies,3
1,thiel,1
2,tessalit,11
3,tambacounda,1
```

**Comment by prabhasp** [comment]
Padding with " " will break csv convention, and make it necessary for
output to be sanitized, so that's not a great idea.

R's name for that first column is row.names, fyi.

**Comment by pld** [comment]
We could also not return the first column, since the ordering is not well defined it doesn't have any real meaning.  Or do you think it is useful?

**Comment by mberg** [comment]
I don't mind making it R friendly.  People will disregard it like the "" if they don't find it helpful anyways.
