### ISSUE TITLE
integers in CSV export

### ISSUE THREAD

**Issue by mberg** [SEL-Columbia/bamboo#349]
I added another count.  Note the hand_pump_count format is decimal vs the water_functioning_count

```
,communities,hand_pump_count,water_functioning_count
0,koumaira,3.0,6
1,garalo,3.0,3
2,ngaundere,3.0,4
3,markala,2.0,4
4,lingeure,1.0,2
```

**Comment by pld** [comment]
Is this a problem?  I do not think importing programs will care and it should not be doing any rounding, if the column had decimals it would show them).  May have to do with the original data format, if any row in the column was a decimal at input they're all decimals, but if none were the column is not.
