### ISSUE TITLE
Support boolean data types

### ISSUE THREAD

**Issue by mberg** [SEL-Columbia/bamboo#358]
If the values for a column are 1 & 0 it might be nice to detect / assume it's boolean for things like summaries instead of just an integer.

**Comment by pld** [comment]
You can use the schema to set the type to a boolean for columns, this issue will make uploading with a fixed schema easier, https://github.com/modilabs/bamboo/issues/408

We may also want to allow user to set the simpletype of columns to boolean after if they do not create a dataset from a schema.
