### ISSUE TITLE
sum in integer summary

### ISSUE THREAD

**Issue by mberg** [SEL-Columbia/bamboo#364]
For the integer and decimal summary types, it might be nice to have sum as an option.

eg) I'd be able to see the total amount below

amount: {
summary: {
count: 22,
std: 4576.514945269335,
min: 500,
max: 14619,
50%: 2422.5,
25%: 1084.25,
75%: 4995.75,
mean: 4282.914545454546
}
},

**Comment by pld** [comment]
These specific results come from a single function call, users can add anything else.  Sum is also easily derived from count and mean.
