### ISSUE TITLE
formhub link not working

### ISSUE THREAD

**Issue by mberg** [SEL-Columbia/bamboo#365]
Adding it here because Renaud thinks the column rewriting might have caused this.

the formhub datasets don't update when new data is submitted to FH.

http://formhub.org/mberg/forms/grades

Here I uploaded a new form, created the rest link then added data.  It created a new dataset proplerly

http://bamboo.io/datasets/09cec6dd7e504839bcd6566358e4b674

But only grabbed the first submission.

In another case, I added the bamboo link to an existing form WITH data.  It successfully imported all the data.  I then created the REST link.  Same problem none of the new submissions worked.

**Comment by pld** [comment]
This doesn't have to do with bamboo since it can't control how submissions are being sent.  If there's a specific dataset and update call that's not working open an issue and attach those files, like https://github.com/modilabs/bamboo/issues/334#issuecomment-11704106
