### ISSUE TITLE
Do not change schema when there are updates with types that differ from schema

### ISSUE THREAD

**Issue by pld** [SEL-Columbia/bamboo#375]
Changing the schema is normal functionality, but
- this is confusing because the schema should be static (agreed?)
- this is also a problem becuase calculations may require a specific type (and an update may not have it)

Three options,
1. change the schema (what happens now, and leads to confusion like #371)
2. reject updates (like Prabhas said, https://github.com/modilabs/bamboo/issues/371#issuecomment-11914717)
3. attempt to parse update as types defined by schema and change schema if parse fails
4. attempt to parse update as types defined by schema and reject if parse fails

(4) seems like the best option, but then we should return whether an update was reject to the request to update, which will mean type checking and attempting to convert synchronously, which will be slower (although probably not too slow).

This resolved #371

**Comment by prabhasp** [comment]
Agreed with (4) being the best option.
This is also the most flexible, once schema updates are implemented.
