### ISSUE TITLE
Dataset info/summary not queryable for dataset with id below (dataset itself is queryable though)

### ISSUE THREAD

**Issue by prabhasp** [SEL-Columbia/bamboo#379]
Dataset is http://bamboo.io/datasets/a10ff9e5380f426fad9576ae0f8a05ca
http://bamboo.io/datasets/a10ff9e5380f426fad9576ae0f8a05ca/info throws a "500 internal server error", so does http://bamboo.io/datasets/a10ff9e5380f426fad9576ae0f8a05ca/summary?select='{%22sex%22:1}'

Is making http://modilabs.github.com/bamboo_js/test.html fail.

**Comment by pld** [comment]
If you download this and upload it locally info shows up fine.  Maybe the DB record is corrupt on the server?  I can see the 500 in the logs but there's no stack trace.

**Comment by prabhasp** [comment]
Hmmm... Mk. No big deal, so we can delete the dataset now. Whoever gets
around to delete can close.

**Comment by pld** [comment]
done
