### ISSUE TITLE
aggregation error in docs

### ISSUE THREAD

**Issue by mberg** [SEL-Columbia/bamboo#380]
Docs say to use

curl -g http://bamboo.io/datasets/8a3d74711475d8a51c84484fe73f24bd151242ea/related

when it should be

curl -g http://bamboo.io/datasets/8a3d74711475d8a51c84484fe73f24bd151242ea/aggregations

I actually think related might be better.

**Comment by pld** [comment]
Can you link to where that is in the docs?  It says aggregations here, http://bamboo.io/docs/basic_commands.html#retrieve-lists-of-aggregated-datasets

Related was good until we had joined and merged datasets, having multiple types of related datasets made it unclear what related meant.

**Comment by mberg** [comment]
Will do.  If you have a few minutes today to maybe chat bamboo before next
week that might be helpful.

Maybe we can do a quick hangout with prabhas and you.

I'm working on a water point working example. I'll push it up shortly to
bamboo-examples to show you.
