### ISSUE TITLE
400 Bad Request response on aggregations url without aggregations specified

### ISSUE THREAD

**Issue by larryweya** [SEL-Columbia/bamboo#384]
Using javascript to access the /aggregations url responds with a 400 error and an empty dict. The 400 forces the XMLHttpRequest into a failed path so we dont know that the aggregations is just empty (unless we explicitly check for the error). I think it should just gracefully return an empty dict.

**Comment by pld** [comment]
The aggregations URL never takes any aggregations, just a dataset ID.  Is this specific to using AJAX?

**Comment by larryweya** [comment]
Its not specific to Ajax, just any http request to the url e.g. If you try this url - http://bamboo.io/datasets/c1746e2ebec1489995a4f9d4b540c7bc/aggregations which doesn't have any aggregations, the page displays open and close curly braces but if you look at the request within the browser's console, it gets a 400 response. Its the same case with calculations.

**Comment by pld** [comment]
Ah, I bet this is a regression on the way the status is set, if you want to dig into the bamboo source it's probably somewhere around here, https://github.com/modilabs/bamboo/blob/master/bamboo/controllers/abstract_controller.py#L54, otherwise I'll look at it tonight.
