### ISSUE TITLE
Deletion on calculation (with a query body) not functioning

### ISSUE THREAD

**Issue by myf** [SEL-Columbia/bamboo#388]
tried on ajax and bamboo_js https://github.com/modilabs/bamboo_js/issues/3, it fails when we put (name=name) in the request data.

**Comment by myf** [comment]
reason: cherrypy default behavior does not support reuqest_body on DELETE, it only supports request_body on "['PUT', 'POST']" (wiki)[https://bitbucket.org/cherrypy/cherrypy/wiki/WhatsNewIn30)
solution: we added DELETE as a method in request.methods_with_bodies in the local config file in cherrypy and it takes body on DELETE now. It however inevitably breaks the param method (e.g. http://bamboo/{id}/calculations?name=name). We ( @myf and @mejymejy ) are thinking to make "deletion with body" as the standard behavior in pybamboo and bamboo_js. shout out if object

**Comment by mejymejy** [comment]
i have the code for this, will push fix once i make sure that python and js libs are working with the changes

**Comment by pld** [comment]
No objection.

The internet seems to agree that having an entity body in a DELETE request is OK, http://stackoverflow.com/questions/299628/is-an-entity-body-allowed-for-an-http-delete-request

We should be consistent in our docs, libraries, and recommendations.  For delete always specify parameters in an entity body, not as parameters.

**Comment by pld** [comment]
https://github.com/modilabs/bamboo/pull/406
