### ISSUE TITLE
Newest aggregation gets messed up after update

### ISSUE THREAD

**Issue by prabhasp** [SEL-Columbia/bamboo#390]
What I did (multiple times):
go to http://formhub.org/prabhasp/forms/Simple_Water_Points -- regenerate a bamboo dataset (temp password for account: testingbamboo) and add the bamboo REST service.

go to http://localhost/ running bamboo.js (UPDATE: branch wp_testing) and type in the following code in the console:

```
var dataset = new bamboo.Dataset({id: 'ID YOU GENERATED HERE'});

dataset.add_calculation('wp_functional', 'newest(submit_date,functional)', 'wp_id');
dataset.add_calculation('latest_submit_date', 'max(submit_date)', 'wp_id');

var aggregatedDatasets = dataset.query_aggregations();
var waterPointDataset = new bamboo.Dataset({id: aggregatedDatasets.aggregations["wp_id"]});

waterPointDataset.query_dataset();
formattedData = _(waterPointDataset.data).map(function(p) { p.latest_submit_date = new Date(p.latest_submit_date * 1000); return p;}) // for date conversion

console.log(formattedData[0], formattedData[1], formattedData[2], formattedData[3]);

So far so good.
```

Things will seem perfect!

```
Object {wp_id: "C", wp_functional: "yes", latest_submit_date: Mon Dec 31 2012 19:00:00 GMT-0500 (EST)}
Object {wp_id: "B", wp_functional: "no", latest_submit_date: Thu Jan 03 2013 19:00:00 GMT-0500 (EST)}
Object {wp_id: "A", wp_functional: "yes", latest_submit_date: Mon Jan 07 2013 19:00:00 GMT-0500 (EST)}
Object {wp_id: "D", wp_functional: "no", latest_submit_date: Thu Jan 03 2013 19:00:00 GMT-0500 (EST)}
```

Now I add another submission (A, functional, Tuesday Jan 08).
And finally, do a refresh of the aggregated dataset:

```
waterPointDataset.query_dataset();
formattedData = _(waterPointDataset.data).map(function(p) { p.latest_submit_date = new Date(p.latest_submit_date * 1000); return p;}) // for date conversion

console.log(formattedData[0], formattedData[1], formattedData[2], formattedData[3]);
```

And output goes to hell.

```
Object {wp_id: "C", wp_functional: "yes", latest_submit_date: Thu Jan 03 2013 19:00:00 GMT-0500 (EST)} 
Object {wp_id: "B", wp_functional: "no", latest_submit_date: Mon Dec 31 2012 19:00:00 GMT-0500 (EST)
Object {wp_id: "A", wp_functional: "yes", latest_submit_date: Thu Jan 03 2013 19:00:00 GMT-0500 (EST)}
Object {wp_id: "D", wp_functional: "no", latest_submit_date: Mon Jan 07 2013 19:00:00 GMT-0500 (EST)}
```

If you look closely, there seems to be some kind of a transposition problem, and the Tuesday Jan 08 date is never pulled in. If you want to look at the data, it is currently [here](http://bamboo.io/datasets/8db48e665fdc494ea69ab90d2aefc341).

**Comment by prabhasp** [comment]
After latest deployments:
this time, looks like the new datapoint is being captured in the calculation, but record transposition is still happening.

Before update, output was:

```
Object {wp_id: "A", wp_functional: "yes", latest_submit_date: Tue Jan 08 2013 00:00:00 GMT+0000 (UTC)}
Object {wp_id: "B", wp_functional: "no", latest_submit_date: Fri Jan 04 2013 00:00:00 GMT+0000 (UTC)}
Object {wp_id: "C", wp_functional: "yes", latest_submit_date: Tue Jan 01 2013 00:00:00 GMT+0000 (UTC)}
Object {wp_id: "D", wp_functional: "no", latest_submit_date: Fri Jan 04 2013 00:00:00 GMT+0000 (UTC)}
```

After update (A, functional, Jan 09), output was:

```
Object {wp_id: "A", wp_functional: "yes", latest_submit_date: Fri Jan 04 2013 00:00:00 GMT+0000 (UTC)}
Object {wp_id: "B", wp_functional: "no", latest_submit_date: Tue Jan 01 2013 00:00:00 GMT+0000 (UTC)}
Object {wp_id: "C", wp_functional: "yes", latest_submit_date: Fri Jan 04 2013 00:00:00 GMT+0000 (UTC)}
Object {wp_id: "D", wp_functional: "no", latest_submit_date: Wed Jan 09 2013 00:00:00 GMT+0000 (UTC)}
```

The `updated_at` on both datasets is matching. I didn't check `updated_at` pre-update, but I did check `num_rows` in the non-aggregated dataset, and that changed as expected (from 20 to 21).

**Comment by pld** [comment]
Next step is to extend this test, https://github.com/modilabs/bamboo/blob/master/bamboo/tests/controllers/test_calculations.py#L396 to replicate the transpositioning.

**Comment by pld** [comment]
I just ran through your test and output looked good.  @prabhasp could you double check and give me an update or close?

**Comment by pld** [comment]
I've been using this to help with the time, http://www.onlineconversion.com/unix_time.htm

**Comment by prabhasp** [comment]
@pld Looking good, w00t!

**Comment by mberg** [comment]
Awesome! Will start kicking the tires again this week. Super excited!

Thanks pld!
