### ISSUE TITLE
email alerts for bamboo.io errors

### ISSUE THREAD

**Issue by mejymejy** [SEL-Columbia/bamboo#397]
who wants in??

**Comment by mberg** [comment]
me

**Comment by pld** [comment]
Let's only send the alerts to a google groups account and then people can join the group to get the alerts.  That way we have a constant setting in the code/config.

**Comment by pld** [comment]
started, https://github.com/modilabs/bamboo/compare/master...email-errors-397

based on docs here, http://docs.cherrypy.org/stable/refman/_cperror.html
