### ISSUE TITLE
joining on different column names: let user specify different on columns per join dataset

### ISSUE THREAD

**Issue by mberg** [SEL-Columbia/bamboo#412]
I've already encountered a situation where I want to join two different datasets on a slug name that's different.  They both represent the same thing id) location_id but the group name around each one was different causing the slug to be different.  I think this will be common when you want to mash two different data sets together that share same codes but different naming conventions in the column.

Could we add support for that?

Also other_dataset_id seems a bit clunky.  Couldn't we just put

`dataset1` and `dataset2`? or `dataset_left` & `dataset_right`?

curl -X POST -d "dataset_id=8123&other_dataset_id=9123&on=food_type" http://bamboo.io/datasets/join

For the multiple joins maybe we could support the following if there are two columns
- `on=food_type,foodtype`
  or 
- `on=['food_type','foodtype']`
  ?

Recommendation:
-  `on=food_type,foodtype`
- `dataset_left` & `dataset_right`

**Comment by prabhasp** [comment]
Matt, could you provide a few rows from the two datasets you were working
with?

On Thu, Jan 17, 2013 at 6:39 AM, Matt Berg notifications@github.com wrote:

> I've already encountered a situation where I want to join two different
> datasets on a slug name that's different. They both represent the same
> thing id) location_id but the group name around each one was different
> causing the slug to be different. I think this will be common when you want
> to mash two different data sets together that share same codes but
> different naming conventions in the column.
> 
> Could we add support for that?
> 
> Also other_dataset_id seems a bit clunky. Couldn't we just put
> 
> dataset1 and dataset2? or dataset_left & dataset_right?
> 
> curl -X POST -d "dataset_id=8123&other_dataset_id=9123&on=food_type"
> http://bamboo.io/datasets/join
> 
> For the multiple joins maybe we could support the following if there are
> two columns
> 
> on=food_type,foodtype
> 
> or
> 
> on=['food_type','foodtype']
> 
> ?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/modilabs/bamboo/issues/412.

## 

Prabhas Pokharel
http://twitter.com/prabhasp
US mobile: +1 347 948 7654
skype/facebook/whatever: prabhasp

**Comment by mberg** [comment]
Here is an example

Table A)

group1_facility_code facility_name

Table)

group2_facility_code facility_name

Does that help or do you need more info?

**Comment by prabhasp** [comment]
The .csv files with a few rows (ie, data not just column names) will make
it easier to whoever is writing the tests.

On Thu, Jan 17, 2013 at 8:29 AM, Matt Berg notifications@github.com wrote:

> Here is an example
> 
> Table A)
> 
> group1_facility_code facility_name
> 
> Table)
> 
> group2_facility_code facility_name
> 
> Does that help or do you need more info?
> 
> On Thu, Jan 17, 2013 at 4:27 PM, prabhasp notifications@github.com
> wrote:
> 
> > Matt, could you provide a few rows from the two datasets you were
> > working
> > with?
> > 
> > On Thu, Jan 17, 2013 at 6:39 AM, Matt Berg notifications@github.com
> > wrote:
> > 
> > > I've already encountered a situation where I want to join two
> > > different
> > > datasets on a slug name that's different. They both represent the same
> > > thing id) location_id but the group name around each one was different
> > > causing the slug to be different. I think this will be common when you
> > > want
> > > to mash two different data sets together that share same codes but
> > > different naming conventions in the column.
> > > 
> > > Could we add support for that?
> > > 
> > > Also other_dataset_id seems a bit clunky. Couldn't we just put
> > > 
> > > dataset1 and dataset2? or dataset_left & dataset_right?
> > > 
> > > curl -X POST -d "dataset_id=8123&other_dataset_id=9123&on=food_type"
> > > http://bamboo.io/datasets/join
> > > 
> > > For the multiple joins maybe we could support the following if there
> > > are
> > > two columns
> > > 
> > > on=food_type,foodtype
> > > 
> > > or
> > > 
> > > on=['food_type','foodtype']
> > > 
> > > ?
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub<
> > > https://github.com/modilabs/bamboo/issues/412>.
> > 
> > ## 
> > 
> > Prabhas Pokharel
> > http://twitter.com/prabhasp
> > US mobile: +1 347 948 7654
> > skype/facebook/whatever: prabhasp
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/modilabs/bamboo/issues/412#issuecomment-12367717>.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/modilabs/bamboo/issues/412#issuecomment-12367800.

## 

Prabhas Pokharel
http://twitter.com/prabhasp
US mobile: +1 347 948 7654
skype/facebook/whatever: prabhasp

**Comment by mberg** [comment]
gotcha will send

**Comment by pld** [comment]
Agreed, those are clunky names, I like `left_dataset`, `right_dataset`.  The type of join you're describing sounds like this feature, #152, but simpler since it is for joins (there is only a the `on` column in each dataset to map).

Different types of interfaces (including @mberg's  suggestions,
- `on=food_type,foodtype`
- `on=[food_type,foodtype]`
- `on=['food_type','foodtype']`
- `left_on=food_type&right_on=foodtype` (assuming we go w/ left and right dataset)
- `dataset1_on=food_type&dataset2_on=foodtype` (assuming we go w/ dataset1 and 2)

others? preferences?

**Comment by mberg** [comment]
strong preferences for one of the first three.    the first one might be
the simplest as there can only be two and everything is sluggified

**Comment by pld** [comment]
that sounds good, there's no reason to introduce syntactic complexity, I'll update the issue
