### ISSUE TITLE
handle async curl calls

### ISSUE THREAD

**Issue by mberg** [SEL-Columbia/bamboo#424]
Not sure if that is the right description but I can load a dataset from google docs into bamboo

This doesn't work for example

curl -X POST -d "https://docs.google.com/spreadsheet/pub?key=0AgpC5gsTSm_4dHBROXFIZGZTYlhGS0N1MGtlcU5aYWc&output=csv" http://bamboo.io/datasets

**Comment by pld** [comment]
The URL format is incorrect.  The ampersand is interpreted as a new parameter, so it needs to be encoded,

`curl -X POST -d "url=https://docs.google.com/spreadsheet/pub?key=0AgpC5gsTSm_4dHBROXFIZGZTYlhGS0N1MGtlcU5aYWc%26output=csv" http://bamboo.io/datasets`

works for me.
