### ISSUE TITLE
Reject calculations with the same name as existing calculations

### ISSUE THREAD

**Issue by pld** [SEL-Columbia/bamboo#425]
Right now they are made unique with underscores, this seems like unexpected behavior for the user.

This is behavior on the:
- POST /calculations/[dataset ID]
- POST /datasets/[dataset ID]/calculations

end points.

**Comment by prabhasp** [comment]
Agree.
Updating the old calculation instead of a rejection is also reasonable
behavior for me.

**Comment by pld** [comment]
This is on POST so I don't think they should update.  (added that to the description as in wasn't made explicit before)
