### ISSUE TITLE
count feature on queries

### ISSUE THREAD

**Issue by rgaudin** [SEL-Columbia/bamboo#432]
[NOT PRIORITY] but would be nice and feels easy to implement.

I find myself doing a lot of len() on the result of custom queries to get the number of rows matching a particular query.

This is very inefficient as I am retrieving thousands of rows (I'd select a single column) just to get a single int.

Obviously, I don't want to go the formula way to do that ; just a count() on the server. I believe it could be done quite easily but I have no idea about how the API should lke like.

**Comment by mberg** [comment]
Could this be in a meta block in the resultset?

**Comment by rgaudin** [comment]
It could but it would still transmit a whole bunch of useless data which is what I'm trying to avoid.
