### ISSUE TITLE
Dataset import failure on mixed int/strings.

### ISSUE THREAD

**Issue by rgaudin** [SEL-Columbia/bamboo#434]
Columns containing mixed int and string might prevent the dataset from being created.
Reproducible by using an IMEI column in FH and using enketo (which puts an error string in the IMEI column).
The dataset is created in "failed" state.

**Comment by MartijnR** [comment]
Can we change the IMEI datatype in bamboo to a string? This way users will get a clear message (as data value 'not supported in enketo') that IMEI's don't work in browsers. Alternatively, we could perhaps add some kind of custom warning in the fh data view and fh browse data view for IMEIs based on a numeric value enketo sets (e.g. value -1).

**Comment by rgaudin** [comment]
Well, so far we are not setting the datatype of the column specifically in bamboo. On CSV upload, it should be automatically guessed which is why there's at least one issue here.

**Comment by pld** [comment]
Can you post an example dataset?

**Comment by prabhasp** [comment]
In general, seems like we should:
- have bamboo fall back to string if ever parsing fails. I realize this is
  more complicated than it sounds.
- get on with formhub bug #574. Renaud, wanna tackle that, and integrate
  into formhub-bamboo integration code next week?

In formhub.R, I treat imei as an R 'factor', even if it's numbers, the
interpretation as an integer seems dubious to me.

**Comment by pld** [comment]
That's what it does now.  There must be a special case that's not handled.

**Comment by pld** [comment]
Looking for an example to get this test to fail, https://github.com/modilabs/bamboo/compare/modilabs:master...modilabs:mixed-434
