### ISSUE TITLE
411 on DELETE dataset

### ISSUE THREAD

**Issue by mejymejy** [SEL-Columbia/bamboo#440]
since we required a body for DELETE requests in order to accommodate deleting calculations by specifying a name in the body, cherrypy is denying (with a 411: content-length required) DELETE requests to /datasets/{id}.  note: this is only happening on dev servers (i.e. those run with scripts/run_server.py) so it may be a discrepancy between dev/prod setups of cherrypy servers.

**Comment by pld** [comment]
What if[/can] you pass the ID as the body of the request?

**Comment by mejymejy** [comment]
i feel like even though this is (apparently) not an issue for bamboo.io, it is still annoying for development servers and also should be resolved because it is an inconsistent use of the DELETE method.  we should either use a body for all DELETE requests or not use a body for all DELETE requests.  i think that it makes more sense to not use a request body for DELETE requests since that is the more typical usage and requiring an empty one when there is nothing that needs to be specified (like in deleting a dataset) is weird.  now, this means that we need to specify the name parameter for calculations in the URL and so we would have to expose the name in the URL like so: `/datasets/{dataset_id}/calculations/{name}`.  what do others think?

**Comment by pld** [comment]
I agree with @mejymejy and recommend we do not use a body for any DELETE requests.  However, I don't like the idea of API implementors needing to remember a specific positional argument.

Made issue #441 for this.
