### ISSUE TITLE
Batch calculating for multiple calculations

### ISSUE THREAD

**Issue by prabhasp** [SEL-Columbia/bamboo#446]
There should be an endpoint which receives a list of calculations. These calculations will be derived from files that look like:

```
solar_functional = has_solar == "yes" and solar_is_functional == "yes"
num_solar_functional = sum(solar_functional) by lga_id
```

and can be transformed to something like

```
[{name: 'solar_functional', formula: 'has_solar == "yes" and solar_is_functional == "yes"'},
 {name: 'num_solar_functional', formula: 'sum(solar_functional)', group: 'lga_id'}]
```

by client libraries. A list of these should be received by bamboo, treated in batch, and i/o should be performed after all calculations are done. Based on performance observation and analysis, thought of as necessary for Nigeria.

[Update: reason I document the original file format here is that an acceptable way of doing this will be to read in a file of the input format. @mejymejy and I thought it is fine for this functionality to go in the clients, if we figure out a common testing paradigm, but having bamboo handle this is also an option].

**Comment by mejymejy** [comment]
I think we should use the same API endpoint for this, that is: `POST /datasets/:dataset_id/calculations` and use another keyword to signify that it is a list of calculations, maybe `json` or something if that is how we are specifying it?

**Comment by pld** [comment]
This is already supported, https://github.com/modilabs/bamboo/blob/master/bamboo/tests/controllers/test_calculations.py#L253

Although it does not try to do batch calculations.

**Comment by prabhasp** [comment]
w00t. less work! (close once batching implemented).
