### ISSUE TITLE
Implement row edits and deletes

### ISSUE THREAD

**Issue by prabhasp** [SEL-Columbia/bamboo#447]
With endpoint: `/datasets/[ID]/row/[INDEX]`

`POST`: create a new row with given index. (index is optional; if not provided, it will be chosen by bamboo)
`PUT`: update the row at the given index
`DELETE`: delete the row at the given index

See https://groups.google.com/d/topic/bamboo-dev/mwsVtIP8O1M/discussion.

**Comment by pld** [comment]
Added to the description to pull in the discussion format as suggest by @prabhasp (also below in this comment).  What do we all think of this format?  Will it be flexible enough going forward?

Implement row edits and deltes with endpoint: `/datasets/[ID]/row/[INDEX]`

`POST`: create a new row with given index. (index is optional; if not provided, it will be chosen by bamboo)
`PUT`: update the row at the given index
`DELETE`: delete the row at the given index

**Comment by prabhasp** [comment]
To update a single cell, you'd pass the entire row, right?

**Comment by pld** [comment]
Or you could pass only the columns being changed as a JSON dict, so only those fields are set to new values.  Usually users will be only editting a proper subset of the columns.  Any column not included as a key is not updated. This forces users to explicitly specify deletion of a column value, by field to empty string (does JSON have a None?), which feels correct.  On the back end we merge the dicts.

**Comment by prabhasp** [comment]
This sounds good. Can we up the priority on this a little bit? The way I see it, it follows perf or other improvements required directly for the Nigeria project.

**Comment by pld** [comment]
Cool, at the top of my list.
