### ISSUE TITLE
datasets with mongo-encoded columns are not decoded for summary

### ISSUE THREAD

**Issue by mejymejy** [SEL-Columbia/bamboo#464]
the column names still appear in the summary as encoded keys

**Comment by pld** [comment]
Is this something new?  Did I maybe mess it up, https://github.com/modilabs/bamboo/commit/ad9624ca4e63f9b6d3b8710647a78ee92ba17e93#diff-3

**Comment by mejymejy** [comment]
not sure if it is new or not... it doesn't really matter if we don't cover it with a test :)

i will have a look and see if i can replicate/test it so we can ensure the functionality in the future

**Comment by pld** [comment]
cool

**Comment by mejymejy** [comment]
see pull #465
