### ISSUE TITLE
A way to get the parent dataset from an aggregated dataset

### ISSUE THREAD

**Issue by pld** [SEL-Columbia/bamboo#473]
- suggest we put a parent_id in the `dataset/[ID]/info`

Is there any privacy reason we wouldn't want to do this?  Maybe we can worry about when/if it arises.

**Comment by mejymejy** [comment]
i don't see an issue, i think that the privacy would be controlled per dataset anyways, so even if you could see where it was, you wouldn't be able to get it.  one question is whether we would want to store the type of child this is.  for example, is it the result of aggregation or merge, etc.

**Comment by pld** [comment]
OK, cool.  I think we should, that would at least be useful for debugging.
