### ISSUE TITLE
Formhub select multiple questions as list types

### ISSUE THREAD

**Issue by larryweya** [SEL-Columbia/bamboo#507]
@pld @mejymejy @rgaudin @ukanga We are currently working on a generic charting dashboard and came across an issue charting "select multiple" questions. Taking our tutorial form as an example, we ask which browsers you use of which we have chrome, firefox, ie and safaris as options where you could pick multiple. Because of our CSV export implementation, these show up as separate questions within bamboo, but we could like to chart this simply as "web_browsers" while right now we and up with "web_browsers_chrome" etc.

We've just implemented export options that allow us to export the select multiple within a single column, space separated i.e. "chrome ie" when only chrome and ie are selected. Is it possible for bamboo to summarize this by doing a count of all instances of IE, then all instances of firefox etc. so that we can say, for this survey with 10 responses, 10 people said they use IE and 10 also said they use Chrome?

We are also meant to implement an sdf schema from formhub for each form, which I will work on that might help bamboo figure out that a certain field contains a list and is not just a space separated response.

**Comment by mberg** [comment]
Larry can you share a snippet of bamboo response to clarify this?

**Comment by prabhasp** [comment]
Also, can you all share design docs, etc. for the charting dashboard? A lot
of work was done here: https://github.com/modilabs/bamboo-meteor-client and
less here: https://github.com/modilabs/bamboo-client that we should
definitely learn from, and I have thought about this a lot, starting with
https://github.com/prabhasp/summarizr

The main two reasons we did not release bamboo-meteor-client were that:
(1) At that time, bamboo was not performant enough to release it. We tried
graphing on nigeria data, and bamboo would choke, as a result of which, we
decided not to release.
(1.5) There wasn't clarity on who we would provide access to these charts
(and therefore the bamboo summary engine). All public datasets on formhub?
All datasets on formhub (but we didn't have auth in place). Etc.

(2) We used meteor, which may not have been the best idea. However, we
could extract out the meteor bits from there, and still have an excellently
functioning dashboard still around.

On Tue, Mar 26, 2013 at 10:00 AM, Matt Berg notifications@github.comwrote:

> Larry can you share a snippet of bamboo response to clarify this?
> 
> On Tue, Mar 26, 2013 at 4:59 PM, Larry Weya notifications@github.comwrote:
> 
> > @pld https://github.com/pld @mejymejy https://github.com/mejymejy
> > @rgaudin https://github.com/rgaudin @ukanga https://github.com/ukangaWe
> > are currently working on a generic charting dashboard and came across an
> > issue charting "select multiple" questions. Taking our tutorial form as
> > an
> > example, we ask which browsers you use of which we have chrome, firefox,
> > ie
> > and safaris as options where you could pick multiple. Because of our CSV
> > export implementation, these show up as separate questions within
> > bamboo,
> > but we could like to chart this simply as "web_browsers" while right now
> > we
> > and up with "web_browsers_chrome" etc.
> > 
> > We've just implemented export options that allow us to export the select
> > multiple within a single column, space separated i.e. "chrome ie" when
> > only
> > chrome and ie are selected. Is it possible for bamboo to summarize this
> > by
> > doing a count of all instances of IE, then all instances of firefox etc.
> > so
> > that we can say, for this survey with 10 responses, 10 people said they
> > use
> > IE and 10 also said they use Chrome?
> > 
> > We are also meant to implement an sdf schema from formhub for each form,
> > which I will work on that might help bamboo figure out that a certain
> > field
> > contains a list and is not just a space separated response.
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/modilabs/bamboo/issues/507>
> > .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/modilabs/bamboo/issues/507#issuecomment-15459600
> .

## 

Prabhas Pokharel
http://prabhasp.com
US mobile: +1 347 948 7654
twitter/skype/facebook/whatever: prabhasp

**Comment by larryweya** [comment]
We have

``` javascript
web_browsers: {
    summary: {
        chrome: 3,
        chrome ie: 1,
        ie: 5,
        firefox safari: 1
    }
}
```

But we want

``` javascript
web_browsers: {
    summary: {
        chrome: 2,
        ie: 6,
        firefox:1,
        safari: 1
    }
}
```

**Comment by prabhasp** [comment]
Actually, do we? I would argue that the top actually gives one more
information, after very light parsing.
An info display on a select_mutliple is a little bit tricky... was just
thinking about it this morning. Figuring out what you want above (which
pipes into a histogram) is straight forward. Tokenize the keys separated by
space, and then re-map the counts, by adding. But then you could do more....
- A graph of the number of browsers people tend to like.
-  You want to not only know which browsers people like, but you might also
  want to know "what browsers people like". Or _part of your visualization_
  might be a cross-tab like the following, which helps figure out _what
  things people like together_ (and if you want it to look pretty, you can
  map it to circle area, or circle radius):
  
  ```
            chrome  firefox  safari  ie
  ```
  
  chrome              -3-
  firefox              0      -0-
  safari               0       1      -0-
  
  ## ie                   1       0       0     -5-
  
  total                4       1       0      5
- Often, people do want to see these cross tabulations: (for example,
  quoting from this issue https://github.com/modilabs/formhub/issues/606, "My
  example: Problem locations for cyclists or pedestrians and sometimes
  both.", where both is seen as as important as either bicycle or pedestrian).

On Tue, Mar 26, 2013 at 10:30 AM, Larry Weya notifications@github.comwrote:

> We have
> 
> web_browsers: {
>     summary: {
>         chrome: 3,
>         chrome ie: 1,
>         ie: 5,
>         firefox safari: 1
>     }}
> 
> But we want
> 
> web_browsers: {
>     summary: {
>         chrome: 2,
>         ie: 6,
>         firefox:1,
>         safari: 1
>     }}
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/modilabs/bamboo/issues/507#issuecomment-15461344
> .

## 

Prabhas Pokharel
http://prabhasp.com
US mobile: +1 347 948 7654
twitter/skype/facebook/whatever: prabhasp

**Comment by pld** [comment]
I agree with Prabhas that this seems like something we would want to do in
post processing, that way we don't remove information.

About list types, at the moment we don't plan on having bamboo support
them, it's an interesting question, a problem is that a nested structure
will make doing reductions more complicated.  I think we'd prefer to
denormalize the data into a matrix format before inserting it.

If this isn't sufficient let's have a discussion about supporting more
complicated data structures in bamboo.

**Comment by mejymejy** [comment]
i agree that the top format gives more useful information and should be left as is.  you can go from top to bottom but not the reverse.  as for list support, i agree with @pld, it should be part of a larger discussion.

**Comment by larryweya** [comment]
Makes some sort sense to do it from the dashboard if we can figure out that
its a list, if we did expose the sdf where we specified that the field was
a list so we can use this in the dashboard, would this be a problem for
bamboo? Just having the simpletype as list?

**Comment by mejymejy** [comment]
it sounds plausible to use `simpletype: list` to denote a list since they are in the [SDF schema](http://www.dataprotocols.org/en/latest/simple-data-format.html#schema-files).  however, this does not give any information as to how the list is annotated, for example: is it JSON? or just strings like we have here?  still, we could translate any of these formats into the format that we have here (space-separated values) for internal bamboo use.  in effect, we would treat a `list` the same as a `string` inside bamboo and pass everything through so that anything consuming the data would know what to do with it.  the other way to do it would be to add a different attribute to the schema that denotes that a given column (still `simpletype: string` in this case) has a list of values.  i tend to think that the column `simpletype` should be a semantic representation of the data and so it makes sense to set it accordingly.  in this case, maybe we just treat lists like strings for the sake of simplicity in bamboo?  if we aren't ok with that then we should add another attribute to deal with further interpretation of data values.

**Comment by larryweya** [comment]
That would work for this use case as we just need to differentiate space
separated lists from strings with spaces in them.

SDF also specifies an object type, I would say a json based list would be
an object?

**Comment by pld** [comment]
A JSON based list sounds like an object to me.  Is there a resolution here?  Can you upload a schema with a simpletype of list, or those bamboo complain?  If it complains, we can add that as a simpletype, after glancing at the code I'm not sure if we check.

Also, what's the priority on this?  Can we move it to 0.6?

**Comment by larryweya** [comment]
On Thu, Apr 11, 2013 at 7:50 AM, Peter Lubell-Doughtie <
notifications@github.com> wrote:

> A JSON based list sounds like an object to me. Is there a resolution here?
> 
> My take is that since on the client side, we need to tell whether a field
> that contains spaces is a list of values or just a string, simpletype ==
> list will denote this.
> 
> Can you upload a schema with a simpletype of list, or those bamboo
> complain? If it complains, we can add that as a simpletype, after glancing
> at the code I'm not sure if we check.
> 
> If an sdf is passed at dataset creation with a simpletype == list,
> bamboo doesn't complain and leaves the simletype as list, which is what we
> want on the client side to differentiate between normal space separated
> strings and space separated lists.

For an object type of list, I would imagine a json structure generated from
a form that has repeats, currently, when we create the initial dataset from
formbub, we provide bamboo with the csv, which for repeats will have
indexed column names for repeats e.g. child[1], child[2]...

I would say the question is how we can display summary data for the child
data, the best way I feel to do this would be via joins, where we would
create a secondary dataset with the child data (or even tertiary dataset
for nested repeats). In which case, I dont see the need for an actual list.

> Also, what's the priority on this? Can we move it to 0.6?
> 
> On the bamboo side, you dont need to do anything, since setting the
> simpletype to list works for us. The only bit that we still need is to have
> the summary data respect the olap type. E.g. we have yes and no represented
> as 1 and 2, which bamboo interprets as a measure, while the sdf indicates
> that its a dimension and we want to use it as a dimension.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/modilabs/bamboo/issues/507#issuecomment-16213627
> .

## 

Larry Weya

**Comment by pld** [comment]
OK, is there an issue for the schema olap_type problem?  Is this the issue, https://github.com/modilabs/bamboo/issues/508?  If not, can you please create an issue and assign it to milestone 0.5.9.  Support for formhub is a bamboo-dev priority.

It sounds like this specific issue is resolved.

**Comment by pld** [comment]
closing
