### ISSUE TITLE
check/remove/refactor uses of Dataset.dframe()

### ISSUE THREAD

**Issue by mejymejy** [SEL-Columbia/bamboo#510]
this queries the database, pulls the entire dataset into memory every time it is called, and can most likely use a select to only get the relevant columns.  if this is not the case, then the operation probably needs to be done in batches in order to avoid memory issues

**Comment by pld** [comment]
duplicate, https://github.com/modilabs/bamboo/issues/456, can we reopen with specific places and ways to remove dframe calls?
