### ISSUE TITLE
calculation deletion takes way too long

### ISSUE THREAD

**Issue by myf** [SEL-Columbia/bamboo#514]
orders of magnitude longer than calculation itself, blaming mongo's findandmodify?

**Comment by myf** [comment]
illustrated
- [2013-04-02 03:33:41,591: INFO/MainProcess] Task bamboo.models.calculation.calculate_task[bf08c1ce-5d16-4685-a2ae-ab98a9b36afb] succeeded in 71.9681060314s: None

vs 
- [2013-04-02 04:41:24,679: INFO/MainProcess] Task bamboo.models.calculation.delete_task[c730b852-ea6c-4247-beff-c15ed489c3cc] succeeded in 3364.72443604s: None

**Comment by pld** [comment]
Was this running on production?
