### ISSUE TITLE
refactor get_children methods to some form of scheme

### ISSUE THREAD

**Issue by mejymejy** [SEL-Columbia/bamboo#517]
the methods in here are very sensitive to the parser. here is how they break down now:
1. no children (`[]`)
2. just the node's value (`[self.value]`)
3. the nodes inside a node's value (`[val for val in self.value]`)
4. chained binary ops (special extraction)
5. the map op special case

some of these are on function ops and some are on term ops (should we have a common base? maybe a Node class since this is now more like a legit parse tree?).

**Comment by pld** [comment]
closed by #526
