### ISSUE TITLE
Support join on datasets with overlapping columns

### ISSUE THREAD

**Issue by pld** [SEL-Columbia/bamboo#530]
Currently bamboo does not support joining datasets with overlapping columns, http://bamboo.io/docs/manipulating_data.html#joining-multiple-datasets.

This is causing issues, especially because a dataset's format may not be custimizable by the client in api situations, e.g. https://github.com/modilabs/formhub/pull/1079.

An example of the exception raised is here, https://github.com/modilabs/bamboo/pull/529.

The reason overlapping columns are not supported is because it is not obvious how to merge them, the question: **What should happen to the overlapping columns when joining datasets?**

Some options:
1. drop the right column, only include the left (or vice-versae, but these are left joins)
2. rename the right column (or left)
3. merge from the right into the left if the left is nil (or vice-versa)
4. drop both the left and right
5. rename both like R, left_column.x right_column.y

I favor 1 or 2.

@rgaudin @mejymejy @myf  @prabhasp what would be most useful for current use cases?

**Comment by rgaudin** [comment]
I'm in favor of `2.` as it's the only one that keeps all the data but maybe we could have options here and let the user decide ? We would still have to decide about the default.

**Comment by pld** [comment]
Do you actually need this?  I misunderstood you're original issue.  If not, let's just close the issue.

**Comment by rgaudin** [comment]
No, I don't _need_ it now but it's probably a good thing to handle it.

**Comment by pld** [comment]
Cool, agreed, we'll put it 0.6.1.

**Comment by prabhasp** [comment]
The way R does it, when it sees conflicts, it renames _both_ left and
right. (In R, they are called x and y). Conflicted `colname` is made into
`colname.x` and `colname.y`, for example. I'd prefer this to renaming only
one or the other side, in our case into `colname.left`, `colname.right`.

On Sunday, April 21, 2013, Peter Lubell-Doughtie wrote:

> Cool, agreed, we'll put it 0.6.1.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/modilabs/bamboo/issues/530#issuecomment-16738813
> .

## 

Prabhas Pokharel
http://prabhasp.com
US mobile: +1 347 948 7654
twitter/skype/facebook/whatever: prabhasp

**Comment by pld** [comment]
Keeping close to R makes sense.  We could go with .x and .y suffixes.  I'm happy with this.
