### ISSUE TITLE
Mongo "$or" queries results in empty lists

### ISSUE THREAD

**Issue by rgaudin** [SEL-Columbia/bamboo#534]
It's probably not a bamboo problem but I can't find where the problem lies so hopefully, you might bring some light.

Queries using the `$or` mongo parameter ([docs](http://docs.mongodb.org/manual/reference/operator/or/)) does not work and returns an empty list `[]`.
## Example

Sample dataset:

```
name,age,location
renaud,30,bamako
ali,39,bamako
richard,32,lyon
jb,30,lyon
```

`curl -X POST -F csv_file=@test.csv http://localhost:8080/datasets`

`$or` queries:

```
reg@elb ~ $ curl -g 'http://localhost:8080/datasets/d44c60b13f61493e84753eb5bd257ec0?query={"$or":[{"location":"bamako"}]}'
[]

reg@elb ~ $ curl -g 'http://localhost:8080/datasets/d44c60b13f61493e84753eb5bd257ec0?query={"$or":[{"location":"bamako"},{"age":30}]}'
[]
```

A simple query:

```
reg@elb ~ $ curl -g 'http://localhost:8080/datasets/d44c60b13f61493e84753eb5bd257ec0?query={"location":"bamako"}'
[{"age": 30, "location": "bamako", "name": "renaud"}, {"age": 39, "location": "bamako", "name": "ali"}]
```

Testing via the mongo shell works though:

```
reg@elb ~ $ mongo bamboo_dev
MongoDB shell version: 2.2.3
connecting to: bamboo_dev
> db.observations.find({"0": "d44c60b13f61493e84753eb5bd257ec0", $or:[{"3":"bamako"}]})
{ "_id" : ObjectId("517553cd1db133048da8b040"), "1" : 0, "0" : "d44c60b13f61493e84753eb5bd257ec0", "3" : "bamako", "2" : 30, "4" : "renaud" }
{ "_id" : ObjectId("517553cd1db133048da8b041"), "1" : 1, "0" : "d44c60b13f61493e84753eb5bd257ec0", "3" : "bamako", "2" : 39, "4" : "ali" }
>
```

which makes me believe that the problem might be in bamboo…

**Comment by rgaudin** [comment]
Well, it's not working from the HTTP interface (yes it's deployed):

```
curl -g 'http://bamboo.io/datasets/212ac0675899458ca69ef3ae7885474a?query={"$or":[{"location":"bamako"}]}'
[]
```

I can't seem to run the tests so it's difficult to investigate. Tests stalls at `test_create_async` despite having `ASYNC_FLAG = 'BAMBOO_ASYNC_OFF'` in the config.

**Comment by pld** [comment]
monit dropped the ball, the new coded wasn't running, the server hadn't restarted, had to do it manually.
