### ISSUE TITLE
need strategy to be able to see labels when there are is a lot of data

### ISSUE THREAD

**Issue by mberg** [SEL-Columbia/bamboo#557]
see:

http://bamboo.io/datasets/f4cf7dfe315146388258702bb4cc95a4/plot?select={%22total_teaching_staff%22:1}&group=district&plot_type=bar

We probably need to incorporate the data into the mouse over. Will do some research to see how other libraries are handling this.

**Comment by pld** [comment]
We might have to use another graphing library for dimensional charts, Rickshaw is specifically built for timeseries so this implementation is sort of a hack.
