### ISSUE TITLE
reset dataset API endpoint

### ISSUE THREAD

**Issue by mejymejy** [SEL-Columbia/bamboo#558]
implement `PUT /datasets/<dataset_id>/reset` which takes the same parameters as `POST /datasets/create` but "re-uses" the `dataset_id`.  internally, this would delete the dataset and create a new one (in the same place) from the data and/or schema passed in.

**Comment by pld** [comment]
Does this need to be a separate endpoint, why not have create take an optional `dataset_id`?

**Comment by pld** [comment]
or both, a reset command as described and if dataset_id is passed to create it acts as if it was a reset command.
