### ISSUE TITLE
JSONP not working

### ISSUE THREAD

**Issue by rgaudin** [SEL-Columbia/bamboo#592]
@pld ; Tried to use JSONP callback with bamboo.io and failed:
- using `&callback=something` results in an empty document.
- using `&jsonp=something` results in a `404`.
- Documentation mentions both.

Dataset:
`http://bamboo.io/datasets/88e96ce2927a48809501a67901fb0edc?select={"elec_by_region":1,"region":1}`

**Comment by rgaudin** [comment]
OK, investigating the problem I can confirm it works with `callback=something` on my local setup.
I've tried to update the code on the server but it has no effect. I'm not sure where the problem lies. Adding deployment label.

**Comment by pld** [comment]
I've been traveling the past 2 weeks. I'll look at this soon, @mejymejy any thoughts?

(Also, maybe we should harden/extend the tests for jsonp and get them to cover more.)

**Comment by pld** [comment]
I've update the docs to remove the `jsonp=` reference, I wonder if this could have something to do with CORS?

**Comment by pld** [comment]
https://github.com/modilabs/bamboo/pull/595
