### ISSUE TITLE
reset endpoint doesn't allow an OPTIONS request

### ISSUE THREAD

**Issue by larryweya** [SEL-Columbia/bamboo#598]
While testing the reset endpoint with bamboo.js, the OPTIONS request returns a 404

**Comment by larryweya** [comment]
@pld Same applies to delete row and update row endpoints

**Comment by pld** [comment]
Looking through `bamboo/config/routes.py` it appears only a subset of endpoints accept an OPTIONS request (they're at the top).

Which endpoints should we allow options requests for? Should we allow options requests for all endpoints?

**Comment by larryweya** [comment]
I'm trying to figure out when an OPTIONS request is sent, both jquery and angular dont to do it on GET requests, however, angular sends one on POST requests.

These are the endpoints that I feel need an OPTIONS request at the moment:
- /datasets
- /datasets/:dataset_id/reset
- /datasets/:dataset_id/row/:index

**Comment by pld** [comment]
OK, will add those, is there any downside to adding it for all of the routes?

**Comment by larryweya** [comment]
I dont see a problem since bamboo doesn't require authentication at the moment I also dont see a security issue.

**Comment by pld** [comment]
I merged and deployed code that adds options for all routes, I don't think there are robust tests for it so not guaranteeing everything is OK.  Can you check it out and let me know if this works for you?
