### ISSUE TITLE
Groups are no longer working

### ISSUE THREAD

**Issue by prabhasp** [SEL-Columbia/bamboo#6]
needed so that I can complete static/bar_graphs.html, which is otherwise almost there.

test process:
- load bar_graphs.html
- open firebug
- on the right hand side, you see a select box, change it; the action should be to hit bamboo with a group url
- see if firebug output includes a json that contains a grouped json summary; doesn't right now.

**Comment by pld** [comment]
This is now fixed, also the API has been checked, check the wiki for how
