### ISSUE TITLE
redirect machine ip to domain name

### ISSUE THREAD

**Issue by mejymejy** [SEL-Columbia/bamboo#60]
right now you can browse the production site at 184.73.235.244 but this should re-route to bamboo.io or whatever we decide to use

**Comment by mberg** [comment]
this has been setup.

On Wed, Jun 6, 2012 at 11:13 AM, Mark Johnston <
reply@reply.github.com

**Comment by mejymejy** [comment]
the domain points to the right ip, but we can still browse the site at the ip itself.  if we put in the ip, it should redirect to the domain (i.e. if i put in http://184.73.235.244/index.html it should redirect to http://bamboo.io/index.html).  should be a simple nginx config update
