### ISSUE TITLE
Use Existing MongoDB Collections

### ISSUE THREAD

**Issue by vamsiikrishna** [SEL-Columbia/bamboo#616]
Hi ,

is there are way to use existing mongodb data, instead of reuploading to bamboo ?

regards

**Comment by prabhasp** [comment]
You could run bamboo yourself; be aware that bamboo assumes quite a bit
about how the collections are organized, so I would recommend re-uploading
via bamboo even when you run the server yourself.

On Sat, Dec 7, 2013 at 9:43 AM, Vamsi notifications@github.com wrote:

> Hi ,
> 
> is there are way to use existing mongodb data, instead of reuploading to
> bamboo ?
> 
> regards
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/SEL-Columbia/bamboo/issues/616
> .

## 

Prabhas Pokharel
http://prabhasp.com
US mobile: +1 347 948 7654
twitter/skype/facebook/whatever: prabhasp
