### ISSUE TITLE
Add information to datasets

### ISSUE THREAD

**Issue by pld** [SEL-Columbia/bamboo#91]
so that it looks like this:

```
/datasets/8a3d74711475d8a51c84484fe73f24bd151242ea
```

returns information about the dataset as JSON,

```
{
  id: DATASET_ID,
  label: NAME,
  description: DESCRIPTION,
  schema: {
    COLUMN_NAME: {
      label: DISPLAY_NAME,
      simpletype: TYPE,
      description: DESCRIPTION
    },
    ...
  },
  license: LICENSE,
  attribution: {
    authors: [author_name, ...],
    credit: CREDIT_STRING
  }
  created_at: CREATE_DATE,
  updated_at: UPDATE_DATE
}
```

**Comment by mejymejy** [comment]
you can now get this info from url:

`/datasets/8a3d74711475d8a51c84484fe73f24bd151242ea/info`

**Comment by mejymejy** [comment]
closing this issue again since a more detailed issue has been filed for the remaining functionality [here](https://github.com/modilabs/bamboo/issues/93).
